### ISSUE TITLE
 "WATCHDOG_NOWAYOUT" feature request

### ISSUE THREAD

**Issue by TroelsTH** [Beckhoff/BBAPI#1]
It seems like the watchdog driver doesn’t check for kernel define WATCHDOG_NOWAYOUT like e.g. the “sch311x_wdt”.
Please add check for the define in the wd_stop function so that the power controller watchdog isn't disabled. This feature is needed to secure that the power controller watchdog catches e.g. kernel panics during shutdown, which otherwise could lead to hung systems.

**Comment by pbruenn** [comment]
Hi Troels,
can you confirm, that commit 403aa85eeccba03a2df5fbbb6849ca2c4f2c188c does what you need?
Regards, Patrick

**Comment by TroelsTH** [comment]
Hi Patrick
I have compiled and verified that your changes work as expected... THANKS
:-)
In particular thanks for the quick response

Best regards
Troels
