### ISSUE TITLE
CX5140 sups support

### ISSUE THREAD

**Issue by ddierick** [Beckhoff/BBAPI#2]
Hi,

Thanks opening up this API on linux! Are there any plans to support the SUPS on the CX5140?

Best regards,

David

**Comment by HWilke** [comment]
Hi David,

currently the BIOS of the CX51x0 has not yet integrated the SUPS support.
Nevertheless you can access a GPIO Input Pin of the CPU which indicates the state.

The GPI for the 1s UPS is located in the IO Area at 0x588 Bit 22. 
0 = Voltage OK
1 = no power

The CPU can only do 4Byte IO-Reads/Writes. Therefore it doesn’t work to read 0x590!
It would be good to test the configuration before by reading 0x580 and 0x584
Bit 22 should be set on both addresses.

I hope that helps you.

Best Regards
Heiko
