### ISSUE TITLE
Error in build

### ISSUE THREAD

**Issue by anpoit00** [Beckhoff/BBAPI#9]
Hello could you say me what is wrong?

Greate Thanks
```
linuxcnc@CX2030:~/BBAPI$ make 
make -C /lib/modules/4.19.0-6-rt-amd64/build M=/home/linuxcnc/BBAPI modules
make[1]: Verzeichnis „/usr/src/linux-headers-4.19.0-6-rt-amd64“ wird betreten
  Building modules, stage 2.
  MODPOST 1 modules
make[1]: Verzeichnis „/usr/src/linux-headers-4.19.0-6-rt-amd64“ wird verlassen
linuxcnc@CX2030:~/BBAPI$ make install
sudo rmmod bbapi_button
rmmod: ERROR: Module bbapi_button is not currently loaded
make: [Makefile:50: unload_all] Fehler 1 (ignoriert)
sudo rmmod bbapi_disp
rmmod: ERROR: Module bbapi_disp is not currently loaded
make: [Makefile:51: unload_all] Fehler 1 (ignoriert)
sudo rmmod bbapi_power
rmmod: ERROR: Module bbapi_power is not currently loaded
make: [Makefile:52: unload_all] Fehler 1 (ignoriert)
sudo rmmod bbapi_sups
rmmod: ERROR: Module bbapi_sups is not currently loaded
make: [Makefile:53: unload_all] Fehler 1 (ignoriert)
sudo rmmod bbapi_wdt
rmmod: ERROR: Module bbapi_wdt is not currently loaded
make: [Makefile:54: unload_all] Fehler 1 (ignoriert)
sudo rmmod bbapi
sudo mkdir -p /lib/modules/4.19.0-6-rt-amd64/extra/
sudo cp ./bbapi.ko /lib/modules/4.19.0-6-rt-amd64/extra/
sudo depmod -a
sudo modprobe bbapi
linuxcnc@CX2030:~/BBAPI$ 

```

**Comment by pbruenn** [comment]
Probably nothing.
Take a look all these errors are ignored. The Makefile was „optimized“ for development. So when you run make install it will try to unload old modules first.
The implementation is not elegant, but was useful at its time;-)


Beckhoff Automation GmbH & Co. KG | Managing Director: Dipl. Phys. Hans Beckhoff
Registered office: Verl, Germany | Register court: Guetersloh HRA 7075

Am 06.12.2019 um 18:21 schrieb anpoit00 <notifications@github.com>:

﻿

Hello could you say me what is wrong?

Greate Thanks

linuxcnc@CX2030:~/BBAPI$ make
make -C /lib/modules/4.19.0-6-rt-amd64/build M=/home/linuxcnc/BBAPI modules
make[1]: Verzeichnis „/usr/src/linux-headers-4.19.0-6-rt-amd64“ wird betreten
  Building modules, stage 2.
  MODPOST 1 modules
make[1]: Verzeichnis „/usr/src/linux-headers-4.19.0-6-rt-amd64“ wird verlassen
linuxcnc@CX2030:~/BBAPI$ make install
sudo rmmod bbapi_button
rmmod: ERROR: Module bbapi_button is not currently loaded
make: [Makefile:50: unload_all] Fehler 1 (ignoriert)
sudo rmmod bbapi_disp
rmmod: ERROR: Module bbapi_disp is not currently loaded
make: [Makefile:51: unload_all] Fehler 1 (ignoriert)
sudo rmmod bbapi_power
rmmod: ERROR: Module bbapi_power is not currently loaded
make: [Makefile:52: unload_all] Fehler 1 (ignoriert)
sudo rmmod bbapi_sups
rmmod: ERROR: Module bbapi_sups is not currently loaded
make: [Makefile:53: unload_all] Fehler 1 (ignoriert)
sudo rmmod bbapi_wdt
rmmod: ERROR: Module bbapi_wdt is not currently loaded
make: [Makefile:54: unload_all] Fehler 1 (ignoriert)
sudo rmmod bbapi
sudo mkdir -p /lib/modules/4.19.0-6-rt-amd64/extra/
sudo cp ./bbapi.ko /lib/modules/4.19.0-6-rt-amd64/extra/
sudo depmod -a
sudo modprobe bbapi
linuxcnc@CX2030:~/BBAPI$
